INSERT INTO user_profiles (user_id, full_name, birthdate, gender, interested_in, interests, zodiac_sign, mbti, country_name, city, locality) VALUES
(1, 'Min Min', '2000-05-10', 'male', 'female', '{"Cars", "Photography", "Entrepreneurship", "Fashion", "Movies", "DIY", "Travel"}', 'Taurus', 'ENTP', 'Myanmar', 'Yangon', 'Bahan'),
(2, 'Lynn Htet Aung', '2003-12-02', 'male', 'female', '{"Music", "Books", "Art", "Design", "Animals"}', 'Sagittarius', 'ISFP', 'Myanmar', 'Yangon', 'Insein'),
(3, 'Sai Cee', '1999-11-15', 'male', 'female', '{"Movies", "Food", "Politics", "Space", "Psychology"}', 'Scorpio', 'INTP', 'Myanmar', 'Yangon', 'South Okkalapa'),
(4, 'Myel Aung', '2002-03-22', 'male', 'female', '{"Education", "Languages", "Dance", "Yoga", "Fashion"}', 'Aries', 'ESTJ', 'Myanmar', 'Yangon', 'Hlaing'),
(5, 'Aung Khant Paing', '2000-06-05', 'male', 'female', '{"Fitness", "Yoga", "Psychology", "Cooking", "Food"}', 'Gemini', 'ENFP', 'Myanmar', 'Yangon', 'Hlaing Thar Yar'),
(6, 'Kaung Pyae', '2004-07-14', 'male', 'female', '{"Music", "Art", "Books", "Writing", "Space"}', 'Cancer', 'INFJ', 'Myanmar', 'Yangon', 'Shwe Pyi That'),
(7, 'Htein Lin Aung', '2004-10-28', 'male', 'female', '{"Music", "Technology", "Fashion", "Nature", "Gaming"}', 'Scorpio', 'ESTP', 'Myanmar', 'Yangon', 'North Okkalapa'),
(8, 'Chaint K Ko', '2004-02-11', 'male', 'female', '{"Technology", "Gaming", "Sports", "Dance", "Animals"}', 'Aquarius', 'INTJ', 'Myanmar', 'Yangon', 'Insein'),
(9, 'Htet Aung', '2003-04-05', 'male', 'female', '{"Food", "Cooking", "History", "Nature", "Books"}', 'Aries', 'ISFJ', 'Myanmar', 'Yangon', 'Bahan'),
(10, 'Kaung Khant', '2002-09-23', 'male', 'female', '{"Technology", "Science", "Gaming", "DIY", "Cars"}', 'Libra', 'ENFJ', 'Myanmar', 'Yangon', 'Lanmadaw'),
(11, 'Thant Zin', '2000-06-21', 'male', 'female', '{"Photography", "Entrepreneurship", "Design", "Fitness", "Cars"}', 'Gemini', 'INFP', 'Myanmar', 'Yangon', 'Latha'),
(12, 'Aung Thet Paing', '1998-12-12', 'male', 'female', '{"Movies", "Books", "Entrepreneurship", "Space", "Psychology"}', 'Sagittarius', 'ENTJ', 'Myanmar', 'Yangon', 'Bo Ta Htaung'),
(13, 'Min Thet Naing', '2001-03-03', 'male', 'female', '{"Yoga", "Philosophy", "Fashion", "Cars", "Science"}', 'Pisces', 'ISFP', 'Myanmar', 'Yangon', 'Hmawbi'),
(14, 'Zayar Min', '1998-01-15', 'male', 'female', '{"History", "Travel", "Books", "Politics", "Space"}', 'Capricorn', 'ISTJ', 'Myanmar', 'Yangon', 'Insein'),
(15, 'Min Thant', '2000-09-29', 'male', 'female', '{"Fitness", "Philosophy", "Languages", "History", "DIY"}', 'Libra', 'INTP', 'Myanmar', 'Yangon', 'Shwe Pyi Thar'),
(16, 'Yan Naing', '1999-05-30', 'male', 'female', '{"Cooking", "Philosophy", "Dance", "Food", "DIY"}', 'Gemini', 'ESTP', 'Myanmar', 'Yangon', 'Hlaing Thar Yar'),
(17, 'Aung Myint Myat', '1999-07-18', 'male', 'female', '{"Science", "Philosophy", "Nature", "Movies", "Food"}', 'Cancer', 'ESFJ', 'Myanmar', 'Yangon', 'Mingalardon'),
(18, 'Nay Myo', '1998-11-22', 'male', 'female', '{"Entrepreneurship", "Philosophy", "Psychology", "Cars", "Art"}', 'Scorpio', 'ISFP', 'Myanmar', 'Yangon', 'Mayangone'),
(19, 'Win Ko Ko', '2004-04-10', 'male', 'female', '{"Movies", "Philosophy", "Writing", "Sports", "Design"}', 'Aries', 'INTP', 'Myanmar', 'Yangon', 'Hlaing'),
(20, 'Paing Phyo', '1999-08-25', 'male', 'female', '{"Sports", "Animals", "Travel", "History", "Fashion"}', 'Virgo', 'ISFJ', 'Myanmar', 'Yangon', 'Hlaing'),
(21, 'Yadanar Bo', '1995-11-15', 'female', 'male', '{"Technology", "Travel", "Photography", "Fashion", "Movies"}', 'Scorpio', 'ENFP', 'Myanmar', 'Yangon', 'Botahtaung'),
(22, 'Khin Wint Wah', '1994-09-21', 'female', 'male', '{"Art", "Design", "Fashion", "Photography", "Music"}', 'Virgo', 'INFJ', 'Myanmar', 'Mandalay', 'Aungmyaythazan'),
(23, 'Phow Mamhe Thar', '1997-05-01', 'female', 'male', '{"Cooking", "Movies", "Animals", "Food", "History"}', 'Taurus', 'ISFJ', 'Myanmar', 'Naypyidaw', 'Ottarathiri'),
(24, 'Phway Phway', '1988-08-09', 'female', 'male', '{"Science", "Books", "Psychology", "Nature", "Fitness"}', 'Leo', 'INTP', 'Myanmar', 'Taunggyi', 'Monghpyak'),
(25, 'Han Thi', '1997-07-25', 'female', 'male', '{"History", "Fitness", "Dance", "Yoga", "Animals"}', 'Leo', 'ENFJ', 'Myanmar', 'Yangon', 'Sanchaung'),
(26, 'Patricia', '1997-12-13', 'female', 'male', '{"Philosophy", "Writing", "Movies", "Books", "Travel"}', 'Sagittarius', 'INTJ', 'Myanmar', 'Mandalay', 'Pyigyidagun'),
(27, 'Naw Phaw Eh Htar', '1996-01-19', 'female', 'male', '{"Space", "Technology", "Education", "Science", "Travel"}', 'Capricorn', 'ENTP', 'Myanmar', 'Bago', 'Pyay'),
(28, 'Yoon Yoon', '2000-01-19', 'female', 'male', '{"Gaming", "Technology", "Movies", "Sports", "Fashion"}', 'Capricorn', 'ISTP', 'Myanmar', 'Yangon', 'Kamayut'),
(29, 'San Yati Moe Myint', '1994-06-03', 'female', 'male', '{"Entrepreneurship", "Fashion", "Cars", "Travel", "Languages"}', 'Gemini', 'ESTJ', 'Myanmar', 'Monywa', 'Chindwin'),
(30, 'Shwe Thamee', '1993-04-18', 'female', 'male', '{"Politics", "Languages", "Food", "Nature", "Design"}', 'Aries', 'ENTJ', 'Myanmar', 'Shwebo', 'Shwebo District'),
(31, 'Honey Nway OO', '1999-03-19', 'female', 'male', '{"Music", "Fashion", "Movies", "Nature", "Yoga"}', 'Pisces', 'ESFJ', 'Myanmar', 'Yangon', 'Insein'),
(32, 'Alice Ong', '1994-08-08', 'female', 'male', '{"Photography", "Sports", "Fitness", "Technology", "Books"}', 'Leo', 'ISFP', 'Myanmar', 'Mandalay', 'Chanmyathazi'),
(33, 'May la Than Zin', '2003-05-23', 'female', 'male', '{"Science", "Gaming", "Writing", "Movies", "DIY"}', 'Gemini', 'INTJ', 'Myanmar', 'Yangon', 'Hlaing'),
(34, 'Hsaung Wutt Yee May', '1995-10-17', 'female', 'male', '{"Languages", "Music", "Travel", "Cooking", "Nature"}', 'Libra', 'ENFP', 'Myanmar', 'Mandalay', 'Mahaaungmyay'),
(35, 'Bobby Soxer', '1993-04-22', 'female', 'male', '{"Books", "Writing", "Technology", "Sports", "Nature"}', 'Taurus', 'INFJ', 'Myanmar', 'Taunggyi', 'Taunggyi District'),
(36, 'Nan Su Yati Soe', '1995-10-24', 'female', 'male', '{"Movies", "Dance", "Fitness", "Yoga", "Technology"}', 'Scorpio', 'ENTP', 'Myanmar', 'Yangon', 'Latha'),
(37, 'Lu Hpring', '2000-01-31', 'female', 'male', '{"Space", "Art", "Books", "Food", "Philosophy"}', 'Aquarius', 'INFP', 'Mexico', 'Guadalajara', 'Centro'),
(38, 'Nay Chi Shoon Lak', '1999-11-13', 'female', 'male', '{"DIY", "Politics", "Writing", "Education", "History"}', 'Virgo', 'ENTJ', 'Myanmar', 'Yangon', 'South Okkalapa'),
(39, 'Pan Yaung Chel', '1996-01-14', 'female', 'male', '{"Yoga", "Dance", "Travel", "Fitness", "Science"}', 'Capricorn', 'ISFP', 'Myanmar', 'Mandalay', 'Kyaukse'),
(40, 'Hsu Eaint San', '1994-03-22', 'female', 'male', '{"Travel", "Technology", "Cars", "Gaming", "Photography"}', 'Aries', 'ENTP', 'Myanmar', 'Yangon', 'Hlaingthaya');
